louvre_ticket_homepage:
    path:     /
    defaults: { _controller: LouvreTicketBundle:Default:index }

louvre_ticket_order:
    path:     /order/create
    defaults: { _controller: LouvreTicketBundle:Ticket:orderCreate }

louvre_ticket_order_two:
    path:     /order/order_two
    defaults: { _controller: LouvreTicketBundle:Ticket:order_twoCreate }

louvre_ticket_order_tree:
    path:     /order/order_tree
    defaults: { _controller: LouvreTicketBundle:Ticket:order_treeCreate }

louvre_ticket_infos:
    path:     /infos
    defaults: { _controller: LouvreTicketBundle:Ticket:infosCreate }

louvre_ticket_mentions:
    path:     /mentions
    defaults: { _controller: LouvreTicketBundle:Ticket:mentionsCreate }